# Generated by Django 3.0.8 on 2020-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('Sprzedaż', 'sell'), ('Kupno', 'buy'), ('Wymiana', 'trade')], max_length=20)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
