# Generated by Django 3.0.8 on 2020-07-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='name',
        ),
    ]
