# Generated by Django 3.0.8 on 2020-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200710_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Sprzedam', 'Sprzedam'), ('Kupię', 'Kupię')], max_length=20),
        ),
    ]
