# Generated by Django 3.0.8 on 2020-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20200712_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
