# Generated by Django 3.1 on 2022-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20221124_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
