# Generated by Django 3.0.8 on 2020-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='item_type',
            field=models.CharField(choices=[('Układ scalony', 'Układ scalony'), ('Półprzewodnik', 'Półprzewodnik'), ('LED', 'LED'), ('Wyświetlacz', 'Wyświetlacz'), ('Element pasywny', 'Element pasywny'), ('Złącze', 'Złącze')], default='LED', max_length=40),
            preserve_default=False,
        ),
    ]
