# Generated by Django 3.1 on 2022-11-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20200719_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_type',
            field=models.CharField(choices=[('Układ scalony', 'Układ scalony'), ('Półprzewodnik', 'Półprzewodnik'), ('Dioda', 'Dioda'), ('Wyświetlacz', 'Wyświetlacz'), ('Element pasywny', 'Element pasywny'), ('Złącze', 'Złącze'), ('Procesor', 'Procesor'), ('Pamięć', 'Pamięć')], max_length=40),
        ),
    ]
